### ISSUE TITLE
Facing issue during Installation

### ISSUE THREAD

**Issue by mdka00001** [uds-helms/PROPORES#13]
I am having an issue installing the tool in my Ubuntu system. 

Error report:

>/home/vagrant/Desktop/thesis/ProPores2/src/pore_id.cpp:27:10: fatal error: filesystem: No such file or directory
 

How shall I fix it?

**Comment by Markus-Hollander** [comment]
Hello,

I’m sorry that you ran into an error. It seems that the compiler cannot find the ‘filesystem’ library. Which version of C++ are you using? Filesystem has been introduced in C++17, so it could be that you are using an older C++ version to compile ProPores. 

Kind regards,

Markus

**Comment by mdka00001** [comment]
Dear Markus,

Thanks for your prompt response. I have fixed the issue. 

My C++ version is 17. However I was using cpp as the compiler. I think for cpp we have to specify the STL as 
"environmental/filesystem" and "-lstdc++fs" as a GCC flag.

However, changing the compiler to g++/gcc fixed the issue. Now I am able to run the commands. This is how i fixed:

>export CC=/usr/bin/gcc-9
>export CXX=/usr/bin/g++-9
>cmake /path_to_project/
>make

Thanks for the assist.

Warm regards,
Md Adnan Karim
