### ISSUE TITLE
Include Hetatm in calculation

### ISSUE THREAD

**Issue by Livia-Rasp** [uds-helms/PROPORES#7]
For now PROPORES excludes hetatms for its calculation. It would useful, if there was an option to include the hetatms.
As in hetatms can be atoms different from C, H, O, N, S, Van der Waals radii for those atoms need to be included in PROPORES.

**Comment by Markus-Hollander** [comment]
Hetero atom support is implemented. Users can now set a flags to skip hetero atoms, skip H-atoms, and to skip non-standard residues in ATOM records. The GUI has been updated accordingly.
